feat: switch from soroban-react to generated libs (#117)
* feat: switch from soroban-react to generated libs

* feat: add ft-contract source; rm `../examples`

- don't use `soroban lab token` to generate/deploy token
- instead, copy example token from examples repo
- remove `../examples` reference in `generate` script
- add `target/bin/soroban` with pinned version of `soroban` to be used
  throughout initialize.sh

* fix: use workspace dependency versions; update sdk

* feat: no more embedding secret keys

This copies ideas from the contract in
https://github.com/AhaLabs/soroban-abundance-token, allowing anyone to
mint themselves tokens. Now this can be used from the frontend directly,
so we no longer need to embed the admin's secret key in the JS. Hooray!

Upon closer inspection, we didn't need any of those constants anymore,
since the contract IDs are embedded in the token libraries.

* fix: add mint_100 and comment out events

* fix: start tryna fix event subscriptions

* fix: update UI after minting 100 ABND

* fix: signAndSend `deposit`; fix modal; update form

The whole page no longer reloads after a pledge. Instead, FormPledge now
takes an `onPledge` param, which it calls after the pledge succeeds.

The now-somewhat-awkward `resultSubmit` has also been filled back out to
match what the modal expects, so the modal looks correct.

* docs: update AlmostUnnecessaryProvider comment

* build: allow newer node versions; improve package name

* build: generate contract clients

* build: fill in .soroban-example-dapp/* first

The CI script needs the values there before it can generate the
libraries, of course.

And the `token_admin*` stuff isn't needed anymore.

* build: install locked CLI version with alias

* build: build contracts before generating clients

* build: s/run-script/run/

Replace `run-script` with the much more common alias `run` to match the
rest of the workflow file

* build: make convert.ts pass strict; exclude target/ from type checking

* build: use node 18 in CI

* build: update lockfile; cat lockfiles during build

* build: switch to yarn; will it work better?

* build: omg yarn works with relative paths but not file:

* build: rm busted debug steps; update docs for yarn

* build: s/yarn ci/yarn install --frozen-lockfile

* build: back to npm we go

* build: switch to postinstall script

* build: rm outdated build step

* build: warn, don't deny, on clippy complaints

and add .cargo/config.toml to match CI settings

* feat: use freighter-api@1.5

* feat: straightforward copy/paste of subscribe logic

This gets the subscriptions working, and finally breaks all dependence
on the @soroban-react packages. The logic is a little confusing, but it
works!

* feat: move subscribe logic to useSubscription hook

This is a hook that can be copy/pasted into other React projects that
need such functionality, to work alongside their generated libraries
until these generated libraries expose subscription logic natively.

* fix: update all relevant UI after pledging

* fix: avoid Freighter error if not yet connected

* fix: can't default build to wasm because tests

* build: use latest soroban-cli

Uses the version with updated freighter-api https://github.com/stellar/soroban-tools/pull/708

* build: use latest cli/soroban-client; rm stellar-base pin

* build: use latest CLI rev from stellar repo

* fix: deal with undefined case

* build: rm RUSTFLAGS from Makefile

Since d771b3f28599664d3e96c313397bb6aad3b71d38, the default settings are
now set in `.cargo/config.toml`

* fix: allow using standalone

Everything looks correct, but when running the app it fails with:

    Error: Cannot connect to insecure soroban-rpc server

* build: update freighter-api

* build: update pinned soroban-cli version

* build(ci): stub .soroban-example-dapp/network

* fix: add 'await'

---------

Co-authored-by: Willem Wyndham <willem@ahalabs.dev>